### ISSUE TITLE
StreamID inspect error

### ISSUE THREAD

**Issue by m0ar** [nathanielc/ceramic-pocket-knife#2]
Hi! Excited to use this tool, but I can't get the `stream-id-inspect` command to work as I get this error with any streamID I can find on cerscan:

```
❯ cpk stream-id-inspect --id kjzl6cwe1jw147k3bqorj08cdpyoxswwpy4xhlux65y0z5q9gw5v27uqv9fivym
Error: unknown variant: 0

❯ cpk stream-id-inspect --id k6zn3rc3v8qin0ybzouzaqu4p560i90fuszcmv9ize9f57lxelm8us01t2louc4nm3r0a49h5ni7ft8hwh4186rdz4ekb5j5dx65n423a1w1on4ri1y10yy
Error: unknown variant: 0
```

Am I missing something critical, or is there a bug spooking? :ghost:

**Comment by nathanielc** [comment]
Thanks for  reporting, there is likely a bug. I'll take a look at this today.

**Comment by m0ar** [comment]
@nathanielc splendid, thanks for the fix :pray:
